name: Lint snippets

on:
  push:
    branches:
      - main
    paths:
      - '.vscode/snippets.code-snippets'
  pull_request:
    branches:
      - main
    paths:
      - '.vscode/snippets.code-snippets'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install pre-commit
        run: pip install pre-commit lychee

      - name: Run pre-commit
        run: pre-commit run --all-files -v
